const CATEGORYData = [
  {
    id: '30',
    category: 'All',
  },
  {
    id: '31',
    category: 'Dishes',
  },
  {
    id: '32',
    category: 'Beverages',
  },
  {
    id: '33',
    category: 'Desserts',
  },
]

const FOODSData = [
  {
    id: '1',
    category: 'Dishes',
    name: 'Adobo',
    time: '🕒 60 mins.',
    capacity: '🍛 5 servings',
    video: 'Ix5Dnud1bl0',
    description:
      'Adobo is a popular Filipino dish made with meat, usually pork, chicken, or beef, that is marinated in vinegar, soy sauce, garlic, and black peppercorns before being slow-cooked in its own juices. The word adobo comes from the Spanish word adobar, which means "to marinate."',
    ingredients: [
      '🛢️  2 tablespoons vegetable oil \n\n',
      '🍗  1 (3 pound) chicken, cut into pieces \n\n',
      '🧅  1 large onion, quartered and sliced \n\n',
      '🧄  2 tablespoons minced garlic \n\n',
      '🧂  ⅔ cup low sodium soy sauce \n\n',
      '🍶  ⅓ cup white vinegar \n\n',
      '🥄  1 tablespoon garlic powder \n\n',
      '🧆  2 teaspoons black pepper \n\n',
      '🍃  1 bay leaf \n\n',
    ],
    instructions: [
      `○ Combine the pork belly, soy sauce, and garlic then marinade for at least 1 hour. \n\n`,
      `○ Heat the pot and put-in the marinated pork belly then cook for a few minutes. \n\n`,
      `○ Pour remaining marinade including garlic. \n\n`,
      `○ Add water, whole pepper corn, and dried bay leaves then bring to a boil. Simmer for 40 minutes to 1 hour or until the pork belly is tender. \n\n`,
      `○ Put-in the vinegar and simmer for 12 to 15 minutes. \n\n`,
      `○ Add salt to taste. \n\n`,
      `○ Serve hot. Share and enjoy! \n\n`,
    ],
    procedure: [
      ` This version suggests marinating the pork to make it more flavorful. Pork belly and other fatty cuts of pork are ideal for this recipe. \n\n`,

      `The first thing to do is marinate the pork belly in soy sauce and crushed garlic. It is best to marinate it overnight. If time is limited, one hour should be enough. Some like to add vinegar during the process. You may do so if preferred. \n\n`,

      `Drain the marinade. Save it for later. The marinated pork needs to be browned. Heat a cooking pot. Add pork with garlic. You can also add a few tablespoons of cooking oil. Cook the pork until it turns brown \n\n`,

      `Cook the pork until tender. Do this by pouring the remaining marinade, if any. Also add water. Let the liquid boil. This is the part where I put the whole peppercorn and dried bay leaves. These ingredient complete my pork adobo. Boiling for 40 minutes should be enough to tenderize the pork. There are times when you have to cook longer. \n\n`,

      `If you have not added the vinegar as part of the marinade, pour it into the pot and let it cook for 10 minutes. Salt is an optional ingredient for this recipe. Use it only if you think it is needed. \n\n`,
    ],
    image: require('assets/images/dishes/adobo.png'),
  },
  {
    id: '2',
    category: 'Dishes',
    name: 'Sinigang',
    time: '🕒 70 mins.',
    capacity: '🍛 6 servings',
    video: 'kIoY0li1ABk',
    description:
      'Sinigang is a Filipino soup or stew characterized by its sour and savory taste. It is most often associated with tamarind (Filipino: sampalok), although it can use other sour fruits and leaves as the souring agent. It is one of the more popular dishes in Filipino cuisine. ',
    ingredients: [
      '🛢️  1 tablespoon vegetable oil \n\n',
      '🧅  1 small onion, chopped \n\n',
      '🥔  1 (½ inch) piece fresh ginger, chopped \n\n',
      '🍅  2 plum tomatoes, cut into ½-inch dice \n\n',
      '🥩  1 pound bone-in pork chops \n\n',
      '💧  4 cups water, more if needed \n\n',
      '🍲  1 (1.41 ounce) package tamarind soup base (such as Knorr®) \n\n',
      '🫑 ½ pound fresh green beans, trimmed \n\n',
    ],
    instructions: [
      `○ Heat oil in a large pot over medium heat. Add onion and ginger; cook and stir until onion is translucent, about 5 minutes. Add tomatoes and pork; cook and stir until pork is browned, about 5 minutes. \n\n`,
      `○ Pour water into the pot; bring to a boil. Stir in tamarind soup base and green beans; reduce heat to medium-low and simmer until pork is tender, about 30 minutes. \n\n`,
      `○ Season with salt and pepper to taste. \n\n`,
    ],
    procedure: [
      `This is a simple recipe for sinigang. It uses pork chops as the main ingredient. It is a good choice for those who want to try sinigang for the first time. \n\n`,
      `The first step is to cook the pork chops. Heat a cooking pot. Add oil. Add onion and ginger. Cook until the onion is translucent. Add tomatoes and pork. Cook until the pork is browned. \n\n`,
      `Pour water into the pot. Bring to a boil. Add tamarind soup base and green beans. Reduce heat to medium-low. Simmer until the pork is tender. \n\n`,
      `Season with salt and pepper to taste. \n\n`,
    ],
    image: require('assets/images/dishes/sinigang.png'),
  },
  {
    id: '3',
    category: 'Dishes',
    name: 'Kare-Kare',
    time: '🕒 90 mins.',
    capacity: '🍛 8 servings',
    video: 'YvTs4on5aVM',
    description:
      'Kare-kare is a Filipino stew made with oxtail, beef, or vegetables, and is thickened with a peanut sauce. It is usually served with bagoong (shrimp paste) and atchara (pickled vegetables).',
    ingredients: [
      '🥩  4 lbs. beef tongue \n\n',
      '💦  3 cups water \n\n',
      '🥜  ¾ cups peanut \n\n',
      '🥐  ¾ cup almonds \n\n',
      '🧅  1 onion minced \n\n',
      '🧄  5 cloves garlic chopped \n\n',
      '🛢️  4 tablespoons annatto oil \n\n',
      '🧂  Salt to taste \n\n',
    ],
    instructions: [
      `○ Boil beef tongue in water for 1 hour. \n\n`,
      `○ Remove beef tongue from water and let cool. \n\n`,
      `○ Peel off the skin and cut into bite size pieces. \n\n`,
      `○ In a blender, blend peanut, almonds, onion, garlic, annatto oil, and salt. \n\n`,
      `○ In a pan, heat oil and saute onion and garlic. \n\n`,
      `○ Add peanut mixture and cook for 5 minutes. \n\n`,
      `○ Add beef tongue and cook for 10 minutes. \n\n`,
      `○ Serve with bagoong and atchara. \n\n`,
    ],
    procedure: [
      `This recipe is a bit time consuming but it is worth the effort. The first step is to boil the beef tongue in water for an hour. This will make the meat tender. \n\n`,
      `Remove the beef tongue from the water and let it cool. Peel off the skin and cut into bite size pieces. \n\n`,
      `In a blender, blend the peanut, almonds, onion, garlic, annatto oil, and salt. \n\n`,
      `In a pan, heat oil and saute onion and garlic. Add the peanut mixture and cook for 5 minutes. \n\n`,
      `Add the beef tongue and cook for 10 minutes. Serve with bagoong and atchara. \n\n`,
    ],

    image: require('assets/images/dishes/karekare.png'),
  },
  {
    id: '4',
    category: 'Dishes',
    name: 'Menudo',
    time: '🕒 80 mins.',
    capacity: '🍛 6 servings',
    video: 'mhdQUSXitLU',
    description:
      'Menudo is a Filipino stew made with tripe, liver, and pork. It is usually served with rice. The stew is flavored with tomato sauce, paprika, and chili peppers. It is often served with a side of pickled papaya.',

    ingredients: [
      '🥩  2 lbs. pork \n\n',
      '🥓  ¼ lb. pig liver \n\n',
      '🥔  1 cup potatoes diced \n\n',
      '🥕  1 piece carrot cubed \n\n',
      '🍶  ½ cup soy sauce \n\n',
      '🍋  ½ piece lemon \n\n',
      '🧅  1 piece onion chopped \n\n',
      '🧄  3 cloves garlic minced \n\n',
      '🥮  1 teaspoon sugar \n\n',
      '🍅  ¾ cup tomato sauce \n\n',
      '💦  1 cup water \n\n',
      '🌭  4 pieces hotdogs sliced diagonally \n\n',
      '🛢️  2 tablespoons cooking oil \n\n',
      '🍁  2 to 3 pieces dried bay leaves \n\n',
      '🧆🧂  Salt and pepper to taste \n\n',
    ],

    instructions: [
      `○ In a pot, boil pork and pig liver in water for 1 hour. \n\n`,
      `○ Remove pork and pig liver from water and let cool. \n\n`,
      `○ Peel off the skin and cut into bite size pieces. \n\n`,
      `○ In a pan, heat oil and saute onion and garlic. \n\n`,
      `○ Add pork, pig liver, potatoes, carrot, soy sauce, lemon, sugar, tomato sauce, and water. \n\n`,
      `○ Add bay leaves and simmer for 30 minutes. \n\n`,
      `○ Add hotdogs and simmer for 5 minutes. \n\n`,
      `○ Season with salt and pepper to taste. \n\n`,
    ],
    procedure: [
      `This recipe is a bit time consuming but it is worth the effort. The first step is to boil the pork and pig liver in water for an hour. This will make the meat tender. \n\n`,
      `Remove the pork and pig liver from the water and let it cool. Peel off the skin and cut into bite size pieces. \n\n`,
      `In a pan, heat oil and saute onion and garlic. Add the pork, pig liver, potatoes, carrot, soy sauce, lemon, sugar, tomato sauce, and water. \n\n`,
      `Add bay leaves and simmer for 30 minutes. Add hotdogs and simmer for 5 minutes. Season with salt and pepper to taste. \n\n`,
    ],
    image: require('assets/images/dishes/menudo.png'),
  },
  {
    id: '5',
    category: 'Dishes',
    name: 'Pinakbet',
    time: '🕒 50 mins.',
    capacity: '🍛 5 servings',
    video: 'OzfTQZVYKmY',
    description:
      'Pinakbet (also called pakbet or pinak bet) is an indigenous Filipino dish from the northern regions of the Philippines. Pinakbet is made from mixed vegetables sautéed in fish or shrimp sauce. The word is the contracted form of the Ilokano word pinakebbet, meaning "shrunk" or "shriveled.',
    ingredients: [
      '🍳  1 lb lechon kawali sliced \n\n',
      '🦐  1 piece Knorr Shrimp Cube \n\n',
      '🌱  12 pieces sitaw cut into 2 inch length \n\n',
      '🍑  ½ piece kalabasa cubed \n\n',
      '🥦  12 pieces okra \n\n',
      '🍆  1 piece Chinese eggplant sliced \n\n',
      '🥒  1 piece ampalaya sliced \n\n',
      '🍅  2 pieces tomato cubed \n\n',
      '🧅  1 piece onion chopped \n\n',
      '🧄  4 cloves garlic crushed \n\n',
      '🍤  2 teaspoons bagoong alamang \n\n',
      '💦  2 ½ cups water \n\n',
      '🛢️  3 tablespoons cooking oil \n\n',
      '🧆  ¼ teaspoon ground black pepper \n\n',
    ],
    instructions: [
      `○ In a pan, heat oil and saute onion and garlic. \n\n`,
      `○ Add lechon kawali and cook for 5 minutes. \n\n`,
      `○ Add sitaw, kalabasa, okra, eggplant, ampalaya, tomato, shrimp cube, bagoong alamang, and water. \n\n`,
      `○ Simmer for 15 minutes. \n\n`,
      `○ Season with ground black pepper. \n\n`,
    ],
    procedure: [
      `In a pan, heat oil and saute onion and garlic. Add lechon kawali and cook for 5 minutes. \n\n`,
      `Add sitaw, kalabasa, okra, eggplant, ampalaya, tomato, shrimp cube, bagoong alamang, and water. Simmer for 15 minutes. \n\n`,
      `Season with ground black pepper. \n\n`,
    ],
    image: require('assets/images/dishes/pinakbet.png'),
  },
  {
    id: '6',
    category: 'Dishes',
    name: 'Lechon Kawali',
    time: '🕒 60 mins.',
    capacity: '🍛 5 servings',
    video: 'MPY9EmLFaR0',
    description:
      'Lechon Kawali,  also known as lechon de carajay or litsong kawali in Tagalog, is a Filipino recipe consisting of pork belly slabs deep-fried in a pan or wok (kawali). It is seasoned beforehand, cooked then served in cubes. It is usually accompanied with a dipping sauce such as sarsa ng litson (lechon sauce) made from vinegar and pork liver or toyomansi (soy sauce with calamansi).',

    ingredients: [
      '🥩  1 ½pounds pork belly \n\n',
      '🧄  3 cloves garlic, crushed \n\n',
      '🍁  2 bay leaves \n\n',
      '🧂  ½ teaspoon salt \n\n',
      '🧆  ½ teaspoon ground black pepper \n\n',
      '🛢️  2 cups oil for frying \n\n',
    ],
    instructions: [
      `○ In a bowl, combine pork belly, garlic, bay leaves, salt, and ground black pepper. \n\n`,
      `○ Marinate for 30 minutes. \n\n`,
      `○ In a pan, heat oil and deep fry pork belly until golden brown. \n\n`,
      `○ Remove pork belly from oil and let cool. \n\n`,
      `○ Cut pork belly into cubes. \n\n`,
    ],
    procedure: [
      `In a bowl, combine pork belly, garlic, bay leaves, salt, and ground black pepper. Marinate for 30 minutes. \n\n`,
      `In a pan, heat oil and deep fry pork belly until golden brown. Remove pork belly from oil and let cool. \n\n`,
      `Cut pork belly into cubes. \n\n`,
    ],
    image: require('assets/images/dishes/lechon.png'),
  },
  {
    id: '7',
    category: 'Dishes',
    name: 'Tinola',
    time: '🕒 50 mins.',
    capacity: '🍛 6 servings',
    video: 'pEMMBceYyMw',
    description:
      'Tinola is a Filipino soup usually served as a main entrée with white rice. Traditionally, this dish is cooked with chicken or fish, wedges of papaya, and leaves of the siling labuyo chili pepper in broth flavored with ginger, onions and fish sauce.',
    ingredients: [
      '🐓  1 whole chicken \n\n',
      '🍛  36 ounces rice washing \n\n',
      '🫑  ½ piece green papaya \n\n',
      '🧄  1 tablespoon garlic minced \n\n',
      '🥔  1 thumb ginger cut into strips \n\n',
      '🍣  2 tablespoon fish sauce \n\n',
      '🌶️  1 cup Hot pepper leaves \n\n',
      '🧆  ¼ teaspoon ground black pepper \n\n',
    ],
    instructions: [
      `○ In a pot, boil chicken with ginger, garlic, and fish sauce. \n\n`,
      `○ Simmer for 30 minutes. \n\n`,
      `○ Add green papaya and simmer for 5 minutes. \n\n`,
      `○ Add hot pepper leaves and simmer for 5 minutes. \n\n`,
      `○ Season with ground black pepper. \n\n`,
    ],
    procedure: [
      `In a pot, boil chicken with ginger, garlic, and fish sauce. Simmer for 30 minutes. \n\n`,
      `Add green papaya and simmer for 5 minutes. \n\n`,
      `Add hot pepper leaves and simmer for 5 minutes. \n\n`,
      `Season with ground black pepper. \n\n`,
    ],
    image: require('assets/images/dishes/tinola.png'),
  },
  {
    id: '8',
    category: 'Dishes',
    name: 'Lumpia',
    time: '🕒 25 mins.',
    capacity: '🍛 9 servings',
    video: 'BIarUjm4U-0',
    description:
      'Lumpia are various types of spring rolls commonly found in the Philippines. Lumpia are made of thin paper-like or crepe-like pastry skin called "lumpia wrapper" enveloping savory or sweet fillings.',
    ingredients: [
      '🐓  50 pieces lumpia wrapper \n\n',
      '🍛  3 cups cooking oil \n\n',
      '🫑  1 ½ lbs ground pork \n\n',
      '🧄  2 pieces onion \n\n',
      '🥔  2 pieces carrots \n\n',
      '🍣  1 ½ teaspoons garlic powder \n\n',
      '🌶️  ½ cup parsley chopped \n\n',
      '🧆  ¼ teaspoon ground black pepper \n\n',
      '🧂  1 ½ teaspoons salt \n\n',
      '🛢️  1 tablespoon sesame oil',
    ],
    instructions: [
      `○ In a bowl, combine ground pork, onion, carrots, garlic powder, parsley, ground black pepper, salt, and sesame oil. \n\n`,
      `○ Mix well. \n\n`,
      `○ In a pan, heat oil and deep fry lumpia wrapper until golden brown. \n\n`,
      `○ Remove lumpia wrapper from oil and let cool. \n\n`,
      `○ Place 1 tablespoon of ground pork mixture in the center of the wrapper. \n\n`,
      `○ Fold the wrapper and roll. \n\n`,
    ],
    procedure: [
      `In a bowl, combine ground pork, onion, carrots, garlic powder, parsley, ground black pepper, salt, and sesame oil. Mix well. \n\n`,
      `In a pan, heat oil and deep fry lumpia wrapper until golden brown. Remove lumpia wrapper from oil and let cool. \n\n`,
      `Place 1 tablespoon of ground pork mixture in the center of the wrapper. Fold the wrapper and roll. \n\n`,
    ],
    image: require('assets/images/dishes/lumpia.png'),
  },
  {
    id: '9',
    category: 'Dishes',
    name: 'Sisig',
    time: '🕒 100 mins.',
    capacity: '🍛 4 servings',
    video: 'kapD-91ZUH8',
    description:
      'Sisig is a Filipino dish made from parts of a pigs face and belly, and chicken liver which is usually seasoned with calamansi, onions, and chili peppers. It originates from the Pampanga region in Luzon.',

    ingredients: [
      '🥩  1 ½ lbs. pork belly boiled for 1 hour \n\n',
      '🥛  ½ cup mayonnaise \n\n',
      '🫑  2 pieces long green pepper chopped \n\n',
      '🧄  2 pieces onion chopped \n\n',
      '🥕  2 pieces carrots \n\n',
      '🧈  ¼ cup margarine \n\n',
      '🌶️  4 pieces chili pepper chopped \n\n',
      '🧆  ½ teaspoon ground black pepper \n\n',
      '🧂  2 tablespoons soy sauce \n\n',
      '🛢️  2 cups cooking oil',
    ],
    instructions: [
      `○ In a bowl, combine pork belly, mayonnaise, green pepper, onion, carrots, margarine, chili pepper, ground black pepper, soy sauce, and cooking oil. \n\n`,
      `○ Mix well. \n\n`,
      `○ In a pan, heat oil and deep fry pork belly until golden brown. \n\n`,
      `○ Remove pork belly from oil and let cool. \n\n`,
      `○ Cut pork belly into cubes. \n\n`,
      `○ In a pan, heat oil and deep fry pork belly until golden brown. \n\n`,
      `○ Remove pork belly from oil and let cool. \n\n`,
      `○ Cut pork belly into cubes. \n\n`,
    ],
    procedure: [
      `In a bowl, combine pork belly, mayonnaise, green pepper, onion, carrots, margarine, chili pepper, ground black pepper, soy sauce, and cooking oil. Mix well. \n\n`,
      `In a pan, heat oil and deep fry pork belly until golden brown. Remove pork belly from oil and let cool. Cut pork belly into cubes. \n\n`,
      `In a pan, heat oil and deep fry pork belly until golden brown. Remove pork belly from oil and let cool. Cut pork belly into cubes. \n\n`,
    ],
    image: require('assets/images/dishes/sisig.png'),
  },
  {
    id: '10',
    category: 'Dishes',
    name: 'Bulalo',
    time: '🕒 200 mins.',
    capacity: '🍛 7 servings',
    video: 'xC0c4fm1KRE',
    description:
      'Bulalo is a beef dish from the Philippines. It is a light colored soup that is made by cooking beef shanks and bone marrow until the collagen and fat has melted into the clear broth. It typically includes leafy vegetables (like pechay or cabbage), corn on the cob, scallions, onions, garlic, ginger, and fish sauce. Potatoes, carrots, or taro can also be added.',
    ingredients: [
      '🍖  2 lbs beef shank \n\n',
      '🥗  ½ cabbage \n\n',
      '🥬  bundle bok choy \n\n',
      '🧄  2 cobs corn \n\n',
      '🫑  2 Tablespoons whole peppercorn \n\n',
      '🌱  ½ cup green onions \n\n',
      '🧅  1 onions \n\n',
      '💦  34 ounces water \n\n',
      '🧂  salt to taste \n\n',
    ],
    instructions: [
      `○ In a pot, add beef shank, cabbage, bok choy, corn, peppercorn, green onions, onions, and water. \n\n`,
      `○ Bring to a boil and simmer for 2 hours. \n\n`,
      `○ Season with salt to taste. \n\n`,
    ],
    procedure: [
      `In a pot, add beef shank, cabbage, bok choy, corn, peppercorn, green onions, onions, and water. Bring to a boil and simmer for 2 hours. Season with salt to taste. \n\n`,
    ],
    image: require('assets/images/dishes/bulalo.png'),
  },
]

const DESSERTSData = [
  {
    id: '11',
    category: 'Desserts',
    name: 'Binatog',
    time: '🕒 25 mins.',
    capacity: '🍛 4 servings',
    video: 'p1TXohnESPc',
    description:
      'Binatog is a Filipino dessert made from glutinous rice flour, coconut milk, and sugar. It is usually served with latik, a sweetened coconut sauce. It is also known as biko, bibingka, and puto bumbong.',
    ingredients: [
      '🌽  29 ounces hominy Mexican style corn \n\n',
      '🛢️  3 tablespoons granulated sugar \n\n',
      '🥥  ¾ cup coconut grated \n\n',
    ],
    instructions: [
      `○ In a pot, add hominy corn and sugar. \n\n`,
      `○ Bring to a boil and simmer for 10 minutes. \n\n`,
      `○ Add coconut and mix well. \n\n`,
    ],
    procedure: [
      `In a pot, add hominy corn and sugar. Bring to a boil and simmer for 10 minutes. Add coconut and mix well. \n\n`,
    ],
    image: require('assets/images/desserts/binatog.png'),
  },
  {
    id: '12',
    category: 'Desserts',
    name: 'Kutsinta',
    time: '🕒 80 mins.',
    capacity: '🍛 6 servings',
    video: 'ukjIP74-hDI',
    description:
      'Puto cuchinta or kutsinta is a type of steamed rice cake found throughout the Philippines. It is made from a mixture of tapioca or rice flour, brown sugar and lye, enhanced with yellow food coloring or annatto extract, and steamed in small ramekins.',
    ingredients: [
      '🌾  1 ½ cup rice flour \n\n',
      '🛢️  ½ cup all-purpose flour \n\n',
      '🥮  1 cup brown sugar \n\n',
      '💧  3 cups water \n\n',
      '💧  1 ½ tsp lye water \n\n',
      '🌱  2 tsp anatto seeds \n\n',
    ],
    instructions: [
      `○ In a bowl, combine rice flour, all-purpose flour, brown sugar, water, lye water, and anatto seeds. \n\n`,
      `○ Mix well. \n\n`,
      `○ In a steamer, add mixture and steam for 30 minutes. \n\n`,
    ],
    procedure: [
      `In a bowl, combine rice flour, all-purpose flour, brown sugar, water, lye water, and anatto seeds. Mix well. In a steamer, add mixture and steam for 30 minutes. \n\n`,
    ],
    image: require('assets/images/desserts/kutsinta.png'),
  },
  {
    id: '13',
    category: 'Desserts',
    name: 'Ginataang Monggo',
    time: '🕒 40 mins.',
    capacity: '🍛 8 servings',
    video: 'jv-ATaGpGBI',
    description:
      'Ginataang munggo, also known as lelut balatung in pampanga or tinutungang munggo, is a Filipino glutinous rice gruel dessert with toasted mung beans, coconut milk, and sugar. It is typically flavored with vanilla or pandan leaves. Corn and fruits like jackfruit or banana may also be added.',
    ingredients: [
      '🌱  ½ cup Mung beans \n\n',
      '🥥  3 cups water \n\n',
      '🌾  ½ cup sticky rice washed (malagkit) \n\n',
      '🥮  6 to 7 tablespoons sugar \n\n',
    ],
    instructions: [
      `○ In a pot, add mung beans and water. \n\n`,
      `○ Bring to a boil and simmer for 20 minutes. \n\n`,
      `○ Add sticky rice and sugar. \n\n`,
      `○ Bring to a boil and simmer for 10 minutes. \n\n`,
    ],
    procedure: [
      `In a pot, add mung beans and water. Bring to a boil and simmer for 20 minutes. Add sticky rice and sugar. Bring to a boil and simmer for 10 minutes. \n\n`,
    ],
    image: require('assets/images/desserts/ginataangmonggo.png'),
  },
  {
    id: '14',
    category: 'Desserts',
    name: 'Palitaw',
    time: '🕒 15 mins.',
    capacity: '🍛 9 servings',
    video: 'GoK3GgqS9Ms',
    description: `Palitaw are called “Palitaw” derived from the word “Litaw” meaning “to float” or “to surface”. This Palitaw Recipe, commonly served in New Year's since it is believed to help the luck to “float up” or show up. This belief came from how Palitaw is cooked in boiling water and floats up when ready. After the sticky rice discs emerge, they are coated with sugar or other flavorings.`,
    ingredients: [
      '🌾  2 cups glutinous rice flour \n\n',
      '🥮  ½ cup granulated sugar \n\n',
      '💦  1 cup water \n\n',
      '🌱  ½ cup sesame seeds roasted \n\n',
      '🥥  1 cup grated coconut \n\n',
    ],
    instructions: [
      `○ In a bowl, add glutinous rice flour, sugar, water, sesame seeds, and grated coconut. \n\n`,
      `○ Mix well. \n\n`,
      `○ In a pot, add mixture and bring to a boil. \n\n`,
      `○ Simmer for 10 minutes. \n\n`,
    ],
    procedure: [
      `In a bowl, add glutinous rice flour, sugar, water, sesame seeds, and grated coconut. Mix well. In a pot, add mixture and bring to a boil. Simmer for 10 minutes. \n\n`,
    ],
    image: require('assets/images/desserts/palitaw.png'),
  },
  {
    id: '15',
    category: 'Desserts',
    name: 'Biko',
    time: '🕒 40 mins.',
    capacity: '🍛 8 servings',
    video: 'ThY66jHY-uI',
    description: `Biko is a sweet rice cake from the Philippines. It is made of coconut milk, brown sugar, ginger, and glutinous rice. It is usually topped with latik. It is a type of kalamay dish and is prepared similarly, except the rice grains are not ground into a paste. They are also sometimes packaged and sold as suman.`,
    ingredients: [
      '🍛  2 cups glutinous rice aka malagkit \n\n',
      '🦐  1 piece Knorr Shrimp Cube \n\n',
      '💦  2 ½ cups water \n\n',
      '🛢️  2 cups brown sugar \n\n',
      '🥥  2 cups brown sugar \n\n',
      '🧂  ½ tsp salt \n\n',
    ],
    instructions: [
      `○ In a pot, add glutinous rice, shrimp cube, water, brown sugar, coconut milk, and salt. \n\n`,
      `○ Bring to a boil and simmer for 20 minutes. \n\n`,
      `○ Add more water if needed. \n\n`,
    ],
    procedure: [
      `In a pot, add glutinous rice, shrimp cube, water, brown sugar, coconut milk, and salt. Bring to a boil and simmer for 20 minutes. Add more water if needed. \n\n`,
    ],
    image: require('assets/images/desserts/biko.png'),
  },
  {
    id: '16',
    category: 'Desserts',
    name: 'Leche Flan',
    time: '🕒 45 mins.',
    capacity: '🍛 4 servings',
    video: 'vN5G2iBUHO0',
    description: `Leche flan is a custard dessert made with milk, eggs, and sugar. It is a popular dessert in the Philippines, where it is known as leche flan. It is also popular in other countries in Southeast Asia, such as Indonesia, Malaysia, Singapore, and Thailand. It is also known as creme caramel in France and Spain.`,
    ingredients: [
      '🥚  10 pieces eggs \n\n',
      '🥛  1 can condensed milk (14 oz) \n\n',
      '🥮  1 cup granulated sugar \n\n',
      '🧂  ½ teaspoon salt \n\n',
      '🌱  1 teaspoon vanilla extract \n\n',
    ],
    instructions: [
      `○ In a bowl, add eggs, condensed milk, sugar, salt, and vanilla extract. \n\n`,
      `○ Mix well. \n\n`,
      `○ In a pot, add mixture and bring to a boil. \n\n`,
      `○ Simmer for 20 minutes. \n\n`,
    ],
    procedure: [
      `In a bowl, add eggs, condensed milk, sugar, salt, and vanilla extract. Mix well. In a pot, add mixture and bring to a boil. Simmer for 20 minutes. \n\n`,
    ],
    image: require('assets/images/desserts/lecheflan.png'),
  },
  {
    id: '17',
    category: 'Desserts',
    name: 'Maja Blanca',
    time: '🕒 35 mins.',
    capacity: '🍛 5 servings',
    video: 'vj_ee_6T6ys',
    description: `Maja Blanca is a Filipino dessert made from coconut milk, cornstarch, and sugar. Often called Coconut Pudding, this luscious dessert is easy to make and the ingredients are very common.Unknown to many, the original Maja Blanca Recipe does not include corn and milk. In this recipe, I added whole sweet kernel corn and condensed milk for added taste and a more creamy texture.Since Christmas season is just around the corner, this would make a very good holiday dessert especially during potluck Christmas Parties and Noche Buena as well.`,
    ingredients: [
      '🥥  4 cups coconut milk \n\n',
      '🛢️  ¾ cup cornstarch \n\n',
      '🥛  14 ounces condensed milk \n\n',
      '🥛  ¾ cup fresh milk \n\n',
      '🥮  ¾ cup granulated sugar \n\n',
      '🌽  15 ounces whole sweet kernel corn \n\n',
      '🥥  5 tbsp toasted grated coconut \n\n',
    ],
    instructions: [
      `○ In a pot, add coconut milk, cornstarch, condensed milk, fresh milk, sugar, and corn. \n\n`,
      `○ Bring to a boil and simmer for 20 minutes. \n\n`,
      `○ Add more milk if needed. \n\n`,
      `○ Serve and top with toasted grated coconut. \n\n`,
    ],
    procedure: [
      `In a pot, add coconut milk, cornstarch, condensed milk, fresh milk, sugar, and corn. Bring to a boil and simmer for 20 minutes. Add more milk if needed. Serve and top with toasted grated coconut. \n\n`,
    ],
    image: require('assets/images/desserts/majablanca.png'),
  },
  {
    id: '18',
    category: 'Desserts',
    name: 'Pastillas de Leche',
    time: '🕒 10 mins.',
    capacity: '🍛 4 servings',
    video: 'myEf53NiqFQ',
    description: `Pastillas de Leche is a Filipino milk candy made from condensed milk, butter, and sugar. It is a popular Filipino dessert and is often served during special occasions like birthdays, Christmas, and New Year. It is also a popular pasalubong or gift to bring home to family and friends.`,
    ingredients: [
      '🥛  2 cups powdered milk sifted \n\n',
      '🥛  1 can 14 ounces condensed milk\n\n',
      '🥮  ½ cup granulated sugar sifted \n\n',
    ],
    instructions: [
      `○ In a pot, add powdered milk, condensed milk, and sugar. \n\n`,
      `○ Bring to a boil and simmer for 5 minutes. \n\n`,
      `○ Pour into a greased pan and let cool. \n\n`,
      `○ Cut into squares and serve. \n\n`,
    ],
    procedure: [
      `In a pot, add powdered milk, condensed milk, and sugar. Bring to a boil and simmer for 5 minutes. Pour into a greased pan and let cool. Cut into squares and serve. \n\n`,
    ],

    image: require('assets/images/desserts/pastillas.png'),
  },
  {
    id: '19',
    category: 'Desserts',
    name: 'Cassava Suman',
    time: '🕒 30 mins.',
    capacity: '🍛 7 servings',
    video: '-CGnGOZznLk',
    description: `Cassava Suman is a Filipino dessert made from grated cassava, coconut milk, and sugar. It is a popular dessert in the Philippines, especially during the Christmas season. It is also a popular pasalubong or gift to bring home to family and friends.`,
    ingredients: [
      '🍥  2 lbs. grated cassava \n\n',
      '🥮  1 ½ cups brown sugar \n\n',
      '🥥  ½ cup coconut cream or coconut milk \n\n',
      '🍌  Banana leaves for wrapping cut into 12 x 6 inch pieces \n\n',
    ],
    instructions: [
      `○ In a pot, add grated cassava, brown sugar, and coconut cream. \n\n`,
      `○ Bring to a boil and simmer for 20 minutes. \n\n`,
      `○ Let cool. \n\n`,
      `○ Wrap in banana leaves and steam for 30 minutes. \n\n`,
    ],
    procedure: [
      `In a pot, add grated cassava, brown sugar, and coconut cream. Bring to a boil and simmer for 20 minutes. Let cool. Wrap in banana leaves and steam for 30 minutes. \n\n`,
    ],
    image: require('assets/images/desserts/cassavasuman.png'),
  },
  {
    id: '20',
    category: 'Desserts',
    name: 'Maruya',
    time: '🕒 10 mins.',
    capacity: '🍛 4 servings',
    video: 'zVCUMZ03V6c',
    description: `Maruya is the perfect snack or dessert! Coated with a fluffy batter and fried to golden perfection, these banana fritters are sure to be a family favorite. It is commonly eat during snack time or merienda. It is also a popular pasalubong or gift to bring home to family and friends.`,
    ingredients: [
      '🍌 6 pieces banana saba or plantain variety, ripe (mashed)\n\n',
      '🌱  1 cup all-purpose flour \n\n',
      '🧈  1 ½ teaspoon vanilla extract \n\n',
      '🥚  1 piece egg beaten \n\n',
      '🛢️  1 teaspoon baking powder\n\n',
      '🥛  1 cup fresh milk \n\n',
      '🛢️  ¾ cup granulated white sugar \n\n',
      '🛢️  ¾ cups cooking oil \n\n',
      '🧂  ½ teaspoon salt \n\n',
    ],
    instructions: [
      `○ In a bowl, add mashed banana, flour, vanilla extract, egg, baking powder, milk, sugar, and salt. \n\n`,
      `○ Mix well. \n\n`,
      `○ Heat oil in a pan. \n\n`,
      `○ Drop batter by spoonfuls into hot oil. \n\n`,
      `○ Fry until golden brown. \n\n`,
      `○ Drain on paper towels. \n\n`,
      `○ Serve and enjoy! \n\n`,
    ],
    procedure: [
      `In a bowl, add mashed banana, flour, vanilla extract, egg, baking powder, milk, sugar, and salt. Mix well. Heat oil in a pan. Drop batter by spoonfuls into hot oil. Fry until golden brown. Drain on paper towels. Serve and enjoy! \n\n`,
    ],
    image: require('assets/images/desserts/maruya.png'),
  },
]

const BEVERAGESData = [
  {
    id: '21',
    category: 'Beverages',
    name: 'Mais Con Yelo',
    time: '🕒 10 mins.',
    capacity: '🍛 5 servings',
    video: 'O7GQGQ3R14U',
    description: `Mais con yelo is a layered dessert consisting of sweet corn, shaved or crushed ice, sweet milk, and a scoop of ice cream. It  is a traditional dessert of crushed ice layered with corn kernels and sweetened milk. It is a popular dessert in the Philippines, especially during the summer season. `,
    ingredients: [
      '🌽  Sweet Corn (canned or Frozen) \n\n',
      '🧊  Shaved Ice \n\n',
      '🥛  Sweetened Condensed Milk \n\n',
      '🥛  Evaporated Milk \n\n',
      '🥮  White Sugar \n\n',
    ],
    instructions: [
      `○ In a bowl, add sweet corn, shaved ice, sweetened condensed milk, evaporated milk, and sugar. \n\n`,
      `○ Mix well. \n\n`,
      `○ Serve and enjoy! \n\n`,
      `○ You can also add a scoop of ice cream on top. \n\n`,
    ],
    procedure: [
      `In a bowl, add sweet corn, shaved ice, sweetened condensed milk, evaporated milk, and sugar. Mix well. Serve and enjoy! You can also add a scoop of ice cream on top. \n\n`,
    ],
    image: require('assets/images/beverages/maisconyelo.png'),
  },
  {
    id: '22',
    category: 'Beverages',
    name: `Sago't Gulaman`,
    time: '🕒 25 mins.',
    capacity: '🍛 6 servings',
    video: '_Bs1QaY',
    description: `A local Filipino beverage made of brown sugar, water, gelatin, and tapioca pearls is called Sago at Gulaman. Sago refers to tapioca pearls while gulaman is the Filipino term for gelatin. This recipe is somewhat a special version because both ingredients are combined together. It is a popular dessert in the Philippines, especially during the summer season. `,
    ingredients: [
      '🧋  3 cups medium tapioca pearls \n\n',
      '🛢️  1 sachet gelatin powder \n\n',
      '🥮  1 cup brown sugar \n\n',
      '🧈  1 tbsp vanilla extract \n\n',
      '💧  2 to 3 cups water \n\n',
    ],
    instructions: [
      `○ In a pot, add tapioca pearls, gelatin powder, brown sugar, vanilla extract, and water. \n\n`,
      `○ Bring to a boil and simmer for 20 minutes. \n\n`,
      `○ Let cool. \n\n`,
      `○ Serve and enjoy! \n\n`,
    ],
    procedure: [
      `In a pot, add tapioca pearls, gelatin powder, brown sugar, vanilla extract, and water. Bring to a boil and simmer for 20 minutes. Let cool. Serve and enjoy! \n\n`,
    ],
    image: require('assets/images/beverages/sagoatgulaman.png'),
  },
  {
    id: '23',
    category: 'Beverages',
    name: 'Halo-Halo',
    time: '🕒 10 mins.',
    capacity: '🍛 8 servings',
    video: 'qS0ceeOHGp8',
    description: `Halo-halo is a famous dessert in the Philippines. It is composed of various ingredients that are all mixed together, along with shaved ice and evaporated milk.
    Some of he common ingredient used to make Halo-halo are sugar palm (kaong), boiled kidney beans, flat rice crisps (pinipig), coconut gel (nata de coco), ripe jackfruit, colored gelatin, tapioca pearls, sweetened plantains, and macapuno.`,
    ingredients: [
      '🍌  1 ripe large banana \n\n',
      '🥭  2 ripe mangoes \n\n',
      '🧊  1 cup firm gelatin set into gel and cut into ½-inch cubes \n\n',
      '🍐  1 cup ripe jackfruit \n\n',
      '🌽  ½ cup sweet corn or chick peas (garbanzos) \n\n',
      '🥥  1 cup young shredded coconut, fresh or canned \n\n',
      '🟣  1 cup cooked sweet yams or (ube halaya) \n\n',
      '🍧  2 cup shaved ice \n\n',
      '🥛  2 cup milk \n\n',
      '🍦  4 scoops of favorite ice cream \n\n',
      '🍛  ½ cup rice pop \n\n',
    ],
    instructions: [
      `○ In a bowl, add banana, mango, gelatin, jackfruit, sweet corn, coconut, yams, shaved ice, milk, ice cream, and rice pop. \n\n`,
      `○ Mix well. \n\n`,
      `○ Serve and enjoy! \n\n`,
    ],
    procedure: [
      `In a bowl, add banana, mango, gelatin, jackfruit, sweet corn, coconut, yams, shaved ice, milk, ice cream, and rice pop. Mix well. Serve and enjoy! \n\n`,
    ],
    image: require('assets/images/beverages/halohalo.png'),
  },
  {
    id: '24',
    category: 'Beverages',
    name: 'Buko Pandan',
    time: '🕒 10 mins.',
    capacity: '🍛 6 servings',
    video: '',
    description: `Buko Pandan is a popular Filipino Dessert made using young coconut,  pandan leaves (or Screwpine leaves), and sago pearls. At first glance, this dessert dish can be mistaken for Buko Salad. Both desserts are almost similar visually. How to Make Buko Pandan Traditionally, this dish is prepared by boiling Pandan leaves in order to extract its essence. The essence is then mixed with coconut milk and sago pearls. `,
    ingredients: [
      '🥥  1 ½ cup young coconut cut into strips \n\n',
      '🥛  5 ounces condensed milk \n\n',
      '🍮  3 ounces powdered gelatin \n\n',
      '💧  1 1/4 cups water \n\n',
      '🥥  6 drops Buko Pandan flavoring \n\n',
      '🍦  2 scoops vanilla ice cream optional \n\n',
      '🧋  ½ cup sago pearls cooked (optional) \n\n',
    ],
    instructions: [
      `○ In a pot, add coconut strips, condensed milk, powdered gelatin, water, and Buko Pandan flavoring. \n\n`,
      `○ Bring to a boil and simmer for 5 minutes. \n\n`,
      `○ Let cool. \n\n`,
      `○ Serve and enjoy! \n\n`,
      `○ You can also add a scoop of ice cream and cooked sago pearls. \n\n`,
    ],
    procedure: [
      `In a pot, add coconut strips, condensed milk, powdered gelatin, water, and Buko Pandan flavoring. Bring to a boil and simmer for 5 minutes. Let cool. Serve and enjoy! You can also add a scoop of ice cream and cooked sago pearls. \n\n`,
    ],
    image: require('assets/images/beverages/bukopandan.png'),
  },
  {
    id: '25',
    category: 'Beverages',
    name: 'Ice Scramble',
    time: '🕒 10 mins.',
    capacity: '🍛 4 servings',
    video: 'bahgrUfZCug',
    description: `Iskrambol, also known as ice scramble, is a Filipino frozen dessert made from shaved ice with banana extract and evaporated milk with sugar It is then topped with a variety of ingredients including powdered milk, marshmallows, strawberry syrup, chocolate syrup, pinipig, tapioca pearls, and sprinkles, among others.`,
    ingredients: [
      '🍧  3-4 cups shaved ice \n\n',
      '🥮  1-2 tbsp sugar \n\n',
      '🥛  1 cup Evaporated milk \n\n',
      '🍌  ½ tsp banana extract/flavoring \n\n',
      '🍎  6-8 drops of red food color for pinkish color \n\n',
      '🍫  Optional Toppings: powdered milk chocolate syrup, strawberry syrup \n\n',
    ],
    instructions: [
      `○ In a bowl, add shaved ice, sugar, evaporated milk, banana extract, and food color. \n\n`,
      `○ Mix well. \n\n`,
      `○ Serve and enjoy! \n\n`,
      `○ You can also add toppings. \n\n`,
    ],
    procedure: [
      `In a bowl, add shaved ice, sugar, evaporated milk, banana extract, and food color. Mix well. Serve and enjoy! You can also add toppings. \n\n`,
    ],
    image: require('assets/images/beverages/icescramble.png'),
  },
  {
    id: '26',
    category: 'Beverages',
    name: 'Taho',
    time: '🕒 45 mins.',
    capacity: '🍛 6 servings',
    video: 'OvQ1tcCQ7x0',
    description: `Tahô is a Philippine snack food made of fresh soft/silken tofu, arnibal, and sago pearl. This staple comfort food is a signature sweet and tahô peddlers can be found all over the country.`,
    ingredients: [
      '🍛  22 ounces soft silken tofu \n\n',
      '🧋  ½ cup sago pearls uncooked (14 oz) \n\n',
      '🥮  1 1/4 cup brown sugar \n\n',
      '💧  4 ½ cups water \n\n',
    ],
    instructions: [
      `○ In a pot, add water, brown sugar, and sago pearls. \n\n`,
      `○ Bring to a boil and simmer for 10 minutes. \n\n`,
      `○ Let cool. \n\n`,
      `○ In a bowl, add silken tofu and sago pearls. \n\n`,
      `○ Mix well. \n\n`,
      `○ Serve and enjoy! \n\n`,
    ],
    procedure: [
      `In a pot, add water, brown sugar, and sago pearls. Bring to a boil and simmer for 10 minutes. Let cool. In a bowl, add silken tofu and sago pearls. Mix well. Serve and enjoy! \n\n`,
    ],

    image: require('assets/images/beverages/taho.png'),
  },
  {
    id: '27',
    category: 'Beverages',
    name: 'Calamansi Juice',
    time: '🕒 10 mins.',
    capacity: '🍛 9 servings',
    video: 'SdanmdctCKI',
    description: `Calamansi Juice is made of freshly squeezed calamondin juice and simple syrup. This Filipino-style limeade is tangy, refreshing, and a delicious way to keep cool all year long. It is a popular drink in the Philippines, especially during the summer season`,
    ingredients: [
      '💧  2-4 cups water \n\n',
      '🥛  1 can 14 ounces condensed milk\n\n',
      '🍋  4 pieces of lemon \n\n',
    ],
    instructions: [
      `○ In a blender, add water, condensed milk, and calamansi. \n\n`,
      `○ Blend until smooth. \n\n`,
      `○ Serve and enjoy! \n\n`,
    ],
    procedure: [
      `In a blender, add water, condensed milk, and calamansi. Blend until smooth. Serve and enjoy! \n\n`,
    ],
    image: require('assets/images/beverages/calamansi.png'),
  },
  {
    id: '28',
    category: 'Beverages',
    name: 'Filipino Salabat',
    time: '🕒 15 mins.',
    capacity: '🍛 4 servings',
    video: 'XDpwjheD_QE',
    description: `Salabat is a traditional Filipino tea made with fresh ginger. The spicy heat of the ginger soothes the sore throat and provides comfort especially during cold and flu seasons. It is also a great way to boost your immune system. `,
    ingredients: [
      '💧  6 cups water \n\n',
      '🟡  4 oz fresh ginger, peeled and sliced into 1/4-inch pieces (about 5 inch piece) \n\n',
      '🐝  1/4 cup honey (or sugar) \n\n',
    ],
    instructions: [
      `○ In a pot, add water and ginger. \n\n`,
      `○ Bring to a boil and simmer for 10 minutes. \n\n`,
      `○ Let cool. \n\n`,
      `○ Strain and add honey. \n\n`,
      `○ Serve and enjoy! \n\n`,
    ],
    procedure: [
      `In a pot, add water and ginger. Bring to a boil and simmer for 10 minutes. Let cool. Strain and add honey. Serve and enjoy! \n\n`,
    ],
    image: require('assets/images/beverages/salabat.png'),
  },
  {
    id: '29',
    category: 'Beverages',
    name: 'Strawberry Wine',
    time: '🕒 20 mins.',
    capacity: '🍛 7 servings',
    video: 'RFnOknANckg',
    description: `Strawberry Wine is a refreshing and fruity wine made with fresh strawberries. It is a great way to use up your leftover strawberries. This wine is perfect for summer parties and gatherings. `,
    ingredients: [
      '🍓  7 pounds whole strawberries\n\n',
      '💧  2 gallons boiling water \n\n',
      '🍋  1 lemon, juiced \n\n',
      '🍷  2 teaspoons wine yeast, optional \n\n',
      '🥮  1 teaspoon baking powder\n\n',
    ],
    instructions: [
      `○ In a large pot, add strawberries and boiling water. \n\n`,
      `○ Let cool. \n\n`,
      `○ Strain and add lemon juice. \n\n`,
      `○ Add wine yeast and baking powder. \n\n`,
      `○ Mix well. \n\n`,
      `○ Cover and let stand for 2 weeks. \n\n`,
      `○ Strain and serve. \n\n`,
    ],
    procedure: [
      `In a large pot, add strawberries and boiling water. Let cool. Strain and add lemon juice. Add wine yeast and baking powder. Mix well. Cover and let stand for 2 weeks. Strain and serve. \n\n`,
    ],
    image: require('assets/images/beverages/strawberrywine.png'),
  },
]

const CAROUSELData = [
  {
    id: '33',
    name: 'Chicken Adobo with 3 bay leaves.',
    time: '⏱️ 60 mins',
    capacity: '🍛 5 servings',
    video: 'aoc1_LwKaUg',
    description:
      'Adobo is a popular Filipino dish made with meat, usually pork, chicken, or beef, that is marinated in vinegar, soy sauce, garlic, and black peppercorns before being slow-cooked in its own juices. The word adobo comes from the Spanish word adobar, which means "to marinate."',
    ingredients: [
      '🛢️  2 tablespoons vegetable oil \n\n',
      '🍗  1 (3 pound) chicken, cut into pieces \n\n',
      '🧅  1 large onion, quartered and sliced \n\n',
      '🧄  2 tablespoons minced garlic \n\n',
      '🧂  ⅔ cup low sodium soy sauce \n\n',
      '🍶  ⅓ cup white vinegar \n\n',
      '🥄  1 tablespoon garlic powder \n\n',
      '🧆  2 teaspoons black pepper \n\n',
      '🍃  1 bay leaf \n\n',
    ],
    instructions: [
      `○ In a large bowl, add chicken, onion, garlic, soy sauce, vinegar, garlic powder, black pepper, and bay leaf. \n\n`,
      `○ Mix well. \n\n`,
      `○ Cover and refrigerate for 1 hour. \n\n`,
      `○ In a large pot, add vegetable oil and chicken. \n\n`,
      `○ Cook over medium heat for 10 minutes. \n\n`,
      `○ Add marinade. \n\n`,
      `○ Cover and simmer for 30 minutes. \n\n`,
      `○ Serve and enjoy! \n\n`,
    ],
    procedure: [
      `In a large bowl, add chicken, onion, garlic, soy sauce, vinegar, garlic powder, black pepper, and bay leaf. Mix well. Cover and refrigerate for 1 hour. In a large pot, add vegetable oil and chicken. Cook over medium heat for 10 minutes. Add marinade. Cover and simmer for 30 minutes. Serve and enjoy! \n\n`,
    ],
    image: require('assets/images/carousel/adobo.png'),
  },
  {
    id: '34',
    name: 'Bulalo with income tax return.',
    time: '⏱️ 200 mins',
    capacity: '🍛 8 servings',
    video: 'xC0c4fm1KRE',
    description:
      'Bulalo is a Filipino beef stew made with beef shanks, marrow bones, and vegetables. It is a popular dish in the Philippines, especially in the Tagalog region. The word bulalo comes from the Spanish word buey, which means "cow."',
    ingredients: [
      '🍖  2 lbs beef shank \n\n',
      '🥗  ½ cabbage \n\n',
      '🥬  bundle bok choy \n\n',
      '🧄  2 cobs corn \n\n',
      '🫑  2 Tablespoons whole peppercorn \n\n',
      '🌱  ½ cup green onions \n\n',
      '🧅  1 onions \n\n',
      '💦  34 ounces water \n\n',
      '🧂  salt to taste \n\n',
    ],
    instructions: [
      `○ In a large pot, add beef shank, cabbage, bok choy, corn, peppercorn, green onions, onions, and water. \n\n`,
      `○ Bring to a boil and simmer for 2 hours. \n\n`,
      `○ Season with salt. \n\n`,
      `○ Serve and enjoy! \n\n`,
    ],
    procedure: [
      `In a large pot, add beef shank, cabbage, bok choy, corn, peppercorn, green onions, onions, and water. Bring to a boil and simmer for 2 hours. Season with salt. Serve and enjoy! \n\n`,
    ],
    image: require('assets/images/carousel/bulalo.png'),
  },
  {
    id: '35',
    name: 'Lechon Kawali with scuba diving. ',
    time: '⏱️ 140 mins',
    capacity: '🍛 5 servings',
    video: 'MPY9EmLFaR0',
    description:
      'Lechon kawali is a popular Filipino dish made with pork belly that is deep-fried until crispy. The word lechon comes from the Spanish word lechón, which means "roast pig."',
    ingredients: [
      '🥩  1 ½pounds pork belly \n\n',
      '🧄  3 cloves garlic, crushed \n\n',
      '🍁  2 bay leaves \n\n',
      '🧂  ½ teaspoon salt \n\n',
      '🧆  ½ teaspoon ground black pepper \n\n',
      '🛢️  2 cups oil for frying \n\n',
    ],
    instructions: [
      `○ In a large bowl, add pork belly, garlic, bay leaves, salt, and black pepper. \n\n`,
      `○ Mix well. \n\n`,
      `○ In a large pot, add oil and heat over medium heat. \n\n`,
      `○ Add pork belly and cook for 10 minutes. \n\n`,
      `○ Flip and cook for another 10 minutes. \n\n`,
      `○ Serve and enjoy! \n\n`,
    ],
    procedure: [
      `In a large bowl, add pork belly, garlic, bay leaves, salt, and black pepper. Mix well. In a large pot, add oil and heat over medium heat. Add pork belly and cook for 10 minutes. Flip and cook for another 10 minutes. Serve and enjoy! \n\n`,
    ],
    image: require('assets/images/carousel/lechon-kawali.png'),
  },
  {
    id: '36',
    name: 'Sisig sa Mang Inasal.',
    time: '⏱️ 100 mins',
    capacity: '🍛 4 servings',
    video: 'kapD-91ZUH8',
    description:
      'Sisig is a popular Filipino dish made with pork that is deep-fried and seasoned with calamansi juice, chili peppers, and onions. The word sisig comes from the Spanish word cebiche, which means "to cook in lime juice."',
    ingredients: [
      '🥩  1 ½ lbs. pork belly boiled for 1 hour \n\n',
      '🥛  ½ cup mayonnaise \n\n',
      '🫑  2 pieces long green pepper chopped \n\n',
      '🧄  2 pieces onion chopped \n\n',
      '🥕  2 pieces carrots \n\n',
      '🧈  ¼ cup margarine \n\n',
      '🌶️  4 pieces chili pepper chopped \n\n',
      '🧆  ½ teaspoon ground black pepper \n\n',
      '🧂  2 tablespoons soy sauce \n\n',
      '🛢️  2 cups cooking oil',
    ],
    instructions: [
      `○ In a large bowl, add pork belly, mayonnaise, green pepper, onion, carrots, margarine, chili pepper, black pepper, soy sauce, and cooking oil. \n\n`,
      `○ Mix well. \n\n`,
      `○ In a large pan, add pork belly mixture and cook over medium heat for 10 minutes. \n\n`,
      `○ Serve and enjoy! \n\n`,
    ],
    procedure: [
      `In a large bowl, add pork belly, mayonnaise, green pepper, onion, carrots, margarine, chili pepper, black pepper, soy sauce, and cooking oil. Mix well. In a large pan, add pork belly mixture and cook over medium heat for 10 minutes. Serve and enjoy! \n\n`,
    ],
    image: require('assets/images/carousel/sisig.png'),
  },
  {
    id: '37',
    name: 'Kare-Kare ni Mare.',
    time: '⏱️ 120 mins',
    capacity: '🍛 6 servings',
    video: 'YvTs4on5aVM',
    description:
      'Kare-kare is a popular Filipino dish made with oxtail, vegetables, and a peanut sauce. The word kare-kare comes from the Spanish word carre, which means "meat."',
    ingredients: [
      '🥩  4 lbs. beef tongue \n\n',
      '💦  3 cups water \n\n',
      '🥜  ¾ cups peanut \n\n',
      '🥐  ¾ cup almonds \n\n',
      '🧅  1 onion minced \n\n',
      '🧄  5 cloves garlic chopped \n\n',
      '🛢️  4 tablespoons annatto oil \n\n',
      '🧂 Salt to taste \n\n',
    ],
    instructions: [
      `○ In a large pot, add beef tongue, water, peanut, almonds, onion, garlic, annatto oil, and salt. \n\n`,
      `○ Bring to a boil and simmer for 2 hours. \n\n`,
      `○ Serve and enjoy! \n\n`,
    ],
    procedure: [
      `In a large pot, add beef tongue, water, peanut, almonds, onion, garlic, annatto oil, and salt. Bring to a boil and simmer for 2 hours. Serve and enjoy! \n\n`,
    ],

    image: require('assets/images/carousel/kare-kare.png'),
  },
  {
    id: '38',
    name: 'Shanghai Naman Dyan.',
    time: '⏱️ 30 mins',
    capacity: '🍛 7 servings',
    video: 'BIarUjm4U-0',
    description: `Shanghai is a popular Filipino dish made with pork and vegetables. The word shanghai comes from the Chinese word shang, which means "up." `,
    ingredients: [
      '🐓  50 pieces lumpia wrapper \n\n',
      '🍛  3 cups cooking oil \n\n',
      '🫑  1 ½ lbs ground pork \n\n',
      '🧄  2 pieces onion \n\n',
      '🥔  2 pieces carrots \n\n',
      '🍣  1 ½ teaspoons garlic powder \n\n',
      '🌶️  ½ cup parsley chopped \n\n',
      '🧆  ¼ teaspoon ground black pepper \n\n',
      '🧂  1 ½ teaspoons salt \n\n',
      '🛢️  1 tablespoon sesame oil',
    ],

    instructions: [
      `○ In a large bowl, add ground pork, onion, carrots, garlic powder, parsley, black pepper, salt, and sesame oil. \n\n`,
      `○ Mix well. \n\n`,
      `○ In a large pan, add cooking oil and heat over medium heat. \n\n`,
      `○ Add ground pork mixture and cook for 5 minutes. \n\n`,
      `○ Serve and enjoy! \n\n`,
    ],
    procedure: [
      `In a large bowl, add ground pork, onion, carrots, garlic powder, parsley, black pepper, salt, and sesame oil. Mix well. In a large pan, add cooking oil and heat over medium heat. Add ground pork mixture and cook for 5 minutes. Serve and enjoy! \n\n`,
    ],
    image: require('assets/images/carousel/lumpia.png'),
  },
  {
    id: '39',
    name: 'Biko kasi ikaw lang BIBI ko.',
    time: '⏱️ 40 mins',
    capacity: '🍛 8 servings',
    video: 'ThY66jHY-uI',
    description:
      'Biko is a popular Filipino dessert made with glutinous rice, coconut milk, and sugar. The word biko comes from the Spanish word bizcocho, which means "cake."',
    ingredients: [
      '🍛  2 cups glutinous rice aka malagkit \n\n',
      '💦  2 ½ cups water \n\n',
      '🛢️  2 cups brown sugar \n\n',
      '🥥  2 cups brown sugar \n\n',
      '🧂  ½ tsp salt \n\n',
    ],
    instructions: [
      `○ In a large pot, add glutinous rice, water, brown sugar, coconut milk, and salt. \n\n`,
      `○ Bring to a boil and simmer for 20 minutes. \n\n`,
      `○ Serve and enjoy! \n\n`,
    ],
    procedure: [
      `In a large pot, add glutinous rice, water, brown sugar, coconut milk, and salt. Bring to a boil and simmer for 20 minutes. Serve and enjoy! \n\n`,
    ],

    image: require('assets/images/carousel/biko.png'),
  },
  {
    id: '40',
    name: 'Leche Flan with prosperity.',
    time: '⏱️ 50 mins',
    capacity: '🍛 9 servings',
    video: 'vN5G2iBUHO0',
    description: `Leche flan is a popular Filipino dessert made with eggs, milk, and sugar. The word leche flan comes from the Spanish word leche flan, which means "milk flan."`,
    ingredients: [
      '🥚  10 pieces eggs \n\n',
      '🥛  1 can condensed milk (14 oz) \n\n',
      '🥮  1 cup granulated sugar \n\n',
      '🧂  ½ teaspoon salt \n\n',
      '🌱  1 teaspoon vanilla extract \n\n',
    ],
    instructions: [
      `○ In a large bowl, add eggs, condensed milk, granulated sugar, salt, and vanilla extract. \n\n`,
      `○ Mix well. \n\n`,
      `○ In a large pan, add water and heat over medium heat. \n\n`,
      `○ Add egg mixture and cook for 30 minutes. \n\n`,
      `○ Serve and enjoy! \n\n`,
    ],
    procedure: [
      `In a large bowl, add eggs, condensed milk, granulated sugar, salt, and vanilla extract. Mix well. In a large pan, add water and heat over medium heat. Add egg mixture and cook for 30 minutes. Serve and enjoy! \n\n`,
    ],
    image: require('assets/images/carousel/lecheflan.png'),
  },
  {
    id: '41',
    name: 'Maja Blanca with Maja Salvador.',
    time: '⏱️ 35 mins',
    capacity: '🍛 10 servings',
    video: 'vj_ee_6T6ys',
    description: `Maja blanca is a popular Filipino dessert made with coconut milk, cornstarch, and sugar. The word maja blanca comes from the Spanish word maja blanca, which means "white maja."`,
    ingredients: [
      '🥥  4 cups coconut milk \n\n',
      '🛢️  ¾ cup cornstarch \n\n',
      '🥛  14 ounces condensed milk \n\n',
      '🥛  ¾ cup fresh milk \n\n',
      '🥮  ¾ cup granulated sugar \n\n',
      '🌽  15 ounces whole sweet kernel corn \n\n',
      '🥥  5 tbsp toasted grated coconut \n\n',
    ],
    instructions: [
      `○ In a large bowl, add coconut milk, cornstarch, condensed milk, fresh milk, granulated sugar, and whole sweet kernel corn. \n\n`,
      `○ Mix well. \n\n`,
      `○ In a large pan, add water and heat over medium heat. \n\n`,
      `○ Add mixture and cook for 30 minutes. \n\n`,
      `○ Serve and enjoy! \n\n`,
    ],
    procedure: [
      `In a large bowl, add coconut milk, cornstarch, condensed milk, fresh milk, granulated sugar, and whole sweet kernel corn. Mix well. In a large pan, add water and heat over medium heat. Add mixture and cook for 30 minutes. Serve and enjoy! \n\n`,
    ],
    image: require('assets/images/carousel/majablanca.png'),
  },
  {
    id: '42',
    name: 'Lulubog lilitaw, Palitaw.',
    time: '⏱️ 45 mins',
    capacity: '🍛 6 servings',
    video: 'GoK3GgqS9Ms',
    description: `Palitaw is a popular Filipino dessert made with glutinous rice, coconut milk, and sugar. The word palitaw comes from the Spanish word palitaw, which means "rice cake."`,
    ingredients: [
      '🌾  2 cups glutinous rice flour \n\n',
      '🥮  ½ cup granulated sugar \n\n',
      '💦  1 cup water \n\n',
      '🌱  ½ cup sesame seeds roasted \n\n',
      '🥥  1 cup grated coconut \n\n',
    ],
    instructions: [
      `○ In a large bowl, add glutinous rice flour, granulated sugar, water, sesame seeds, and grated coconut. \n\n`,
      `○ Mix well. \n\n`,
      `○ In a large pan, add water and heat over medium heat. \n\n`,
      `○ Add mixture and cook for 30 minutes. \n\n`,
      `○ Serve and enjoy! \n\n`,
    ],
    procedure: [
      `In a large bowl, add glutinous rice flour, granulated sugar, water, sesame seeds, and grated coconut. Mix well. In a large pan, add water and heat over medium heat. Add mixture and cook for 30 minutes. Serve and enjoy! \n\n`,
    ],

    image: require('assets/images/carousel/palitaw.png'),
  },
  {
    id: '43',
    name: 'Taho para sa mga taong naglaho.',
    time: '⏱️ 45 mins',
    capacity: '🍛 10 servings',
    video: 'OvQ1tcCQ7x0',
    description: `Taho is a popular Filipino dessert made with tofu, sweet syrup, and tapioca pearls. The word taho comes from the Spanish word taho, which means "tofu."`,
    ingredients: [
      '🍛  22 ounces soft silken tofu \n\n',
      '🧋  ½ cup sago pearls uncooked (14 oz) \n\n',
      '🥮  1 1/4 cup brown sugar \n\n',
      '💧  4 ½ cups water \n\n',
    ],
    instructions: [
      `○ In a large bowl, add soft silken tofu, sago pearls, brown sugar, and water. \n\n`,
      `○ Mix well. \n\n`,
      `○ In a large pan, add water and heat over medium heat. \n\n`,
      `○ Add mixture and cook for 30 minutes. \n\n`,
      `○ Serve and enjoy! \n\n`,
    ],
    procedure: [
      `In a large bowl, add soft silken tofu, sago pearls, brown sugar, and water. Mix well. In a large pan, add water and heat over medium heat. Add mixture and cook for 30 minutes. Serve and enjoy! \n\n`,
    ],
    image: require('assets/images/carousel/taho.png'),
  },
  {
    id: '44',
    name: 'Ice Scramble with oven toaster.',
    time: '⏱️ 10 mins',
    capacity: '🍛 5 servings',
    video: 'V_voSJmeXIs',
    description: `Ice scramble is a popular Filipino dessert made with ice cream, milk, and sugar. The word ice scramble comes from the Spanish word ice scramble, which means "ice scramble."`,
    ingredients: [
      '🍧  3-4 cups shaved ice \n\n',
      '🥮  1-2 tbsp sugar \n\n',
      '🥛  1 cup Evaporated milk \n\n',
      '🍌  ½ tsp banana extract/flavoring \n\n',
      '🍎  6-8 drops of red food color for pinkish color \n\n',
      '🍫  Optional Toppings: powdered milk chocolate syrup, strawberry syrup \n\n',
    ],
    instructions: [
      `○ In a large bowl, add shaved ice, sugar, evaporated milk, banana extract, and red food color. \n\n`,
      `○ Mix well. \n\n`,
      `○ In a large pan, add water and heat over medium heat. \n\n`,
      `○ Add mixture and cook for 30 minutes. \n\n`,
      `○ Serve and enjoy! \n\n`,
    ],
    procedure: [
      `In a large bowl, add shaved ice, sugar, evaporated milk, banana extract, and red food color. Mix well. In a large pan, add water and heat over medium heat. Add mixture and cook for 30 minutes. Serve and enjoy! \n\n`,
    ],

    image: require('assets/images/carousel/icescramble.png'),
  },
  {
    id: '45',
    name: 'Salabat with life insurance.',
    time: '⏱️ 15 mins',
    capacity: '🍛 4 servings',
    video: 'XDpwjheD_QE',
    description: `Salabat is a popular Filipino dessert made with ginger, sugar, and water. The word salabat comes from the Spanish word salabat, which means "ginger."`,
    ingredients: [
      '💧  6 cups water \n\n',
      '🟡  4 oz fresh ginger, peeled and sliced into 1/4-inch pieces (about 5 inch piece) \n\n',
      '🐝  1/4 cup honey (or sugar) \n\n',
    ],
    instructions: [
      `○ In a large bowl, add water, fresh ginger, and honey. \n\n`,
      `○ Mix well. \n\n`,
      `○ In a large pan, add water and heat over medium heat. \n\n`,
      `○ Add mixture and cook for 30 minutes. \n\n`,
      `○ Serve and enjoy! \n\n`,
    ],
    procedure: [
      `In a large bowl, add water, fresh ginger, and honey. Mix well. In a large pan, add water and heat over medium heat. Add mixture and cook for 30 minutes. Serve and enjoy! \n\n`,
    ],

    image: require('assets/images/carousel/salabat.png'),
  },
  {
    id: '46',
    name: 'Sago at gulaman good manners.',
    time: '⏱️ 10 mins',
    capacity: '🍛 5 servings',
    video: 'OAAV_Bs1QaY',
    description: `Sago at gulaman is a popular Filipino dessert made with sago, gelatin, and sugar. The word sago at gulaman comes from the Spanish word sago at gulaman, which means "sago and gelatin."`,
    ingredients: [
      '🧋  3 cups medium tapioca pearls \n\n',
      '🛢️  1 sachet gelatin powder \n\n',
      '🥮  1 cup brown sugar \n\n',
      '🧈  1 tbsp vanilla extract \n\n',
      '💧  2 to 3 cups water \n\n',
    ],
    instructions: [
      `○ In a large bowl, add medium tapioca pearls, gelatin powder, brown sugar, vanilla extract, and water. \n\n`,
      `○ Mix well. \n\n`,
      `○ In a large pan, add water and heat over medium heat. \n\n`,
      `○ Add mixture and cook for 30 minutes. \n\n`,
      `○ Serve and enjoy! \n\n`,
    ],
    procedure: [
      `In a large bowl, add medium tapioca pearls, gelatin powder, brown sugar, vanilla extract, and water. Mix well. In a large pan, add water and heat over medium heat. Add mixture and cook for 30 minutes. Serve and enjoy! \n\n`,
    ],
    image: require('assets/images/carousel/sagoatgulaman.png'),
  },
]

export { FOODSData, CATEGORYData, CAROUSELData, DESSERTSData, BEVERAGESData }
